application: pfif-tools
version: 2
runtime: python37
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /validate
  static_files: static/validator.html
  upload: static/validator.html
- url: /diff
  static_files: static/diff.html
  upload: static/diff.html
- url: /.*
  script: wsgi.application

# App Engine uses gunicorn by default, but it looks for an entrypoint at
# main.app. We specify entrypoint to direct it to wsgi.application.
entrypoint: gunicorn -b :$PORT wsgi:application
