application: pfif-tools
version: 2
runtime: python37
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: wsgi.application

# App Engine uses gunicorn by default, but it looks for an entrypoint at
# main.app. We specify entrypoint to direct it to wsgi.application.
entrypoint: gunicorn -b :$PORT wsgi:application
